name: 'Setup GCP CI/CD Pipeline on GCP Cloud Build'
on:
  push:
    branches:
      - 'develop'
  workflow_dispatch:
    branches: ["develop"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: repository-name
        uses: ASzc/change-string-case-action@v5
        with:
          string: '${{ github.event.repository.name }}'
      - id: branch-name
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.GITHUB_REF_NAME }}
      - name: 'Debug Repo Name'
        run: echo ${{ steps.repository-name.outputs.lowercase }}
      - name: 'Debug Branch'
        run: echo ${{ steps.branch-name.outputs.lowercase }}
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_DEV_CREDENTIALS }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          install_components: 'beta'
      - name: 'Create Artifactory'
        run: 'gcloud artifacts repositories create ${{ steps.repository-name.outputs.lowercase }}  
              --repository-format=docker 
              --location=europe-west2 
              --description="Docker repository for ${{ github.event.repository.name }}" || true '
      - name: 'Create GCP Cloud Build Trigger for Git Flow'
        run: 'gcloud beta builds triggers create github --name="${{ github.event.repository.name }}-GitFlow-Trigger" 
              --repo-owner="shara-inc" 
              --description="Trigger for repo:${{ github.event.repository.name }} Git Flow Branches" 
              --substitutions="_SEVERITY=MEDIUM,_SONARHOST="https://sonarcloud.io",_REPOSITORY=${{ steps.repository-name.outputs.lowercase }}"
              --branch-pattern="^(feature|bugfix|hotfix|chore|support|release).*" 
              --repo-name="${{ github.event.repository.name }}" 
              --build-config="cloudbuild.yaml" || true '